import puppeteer from "puppeteer-core";
const COOKIE = "edf8pbDwQpBJ72wAMuVRDid9bf44bpGR.gO8Aoh4wYu%2BsDfFXiNzN0BMb55l9YhCUz2d3SGXjiZk%3D";
const sleep = ms => new Promise(r=>setTimeout(r,ms));
const b = await puppeteer.launch({ executablePath:"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", headless:"new", args:["--no-sandbox"] });
const p = await b.newPage();
await p.setViewport({ width:414, height:720, deviceScaleFactor:2 });
await p.setCookie({ name:"better-auth.session_token", value:COOKIE, domain:"localhost", path:"/" });
await p.goto("http://localhost:3002/dashboard/employee", { waitUntil:"networkidle0", timeout:30000 });
await sleep(1300);
await p.evaluate(()=>{const el=[...document.querySelectorAll('.cursor-pointer')].find(e=>/Bright Spot/.test(e.textContent||''));el&&el.click();});
await sleep(1100); await p.screenshot({ path:"/tmp/tame-bright.png" });
await b.close(); console.log("done");
