import puppeteer from "puppeteer-core";
const COOKIE = "edf8pbDwQpBJ72wAMuVRDid9bf44bpGR.gO8Aoh4wYu%2BsDfFXiNzN0BMb55l9YhCUz2d3SGXjiZk%3D";
const sleep = ms => new Promise(r=>setTimeout(r,ms));
const b = await puppeteer.launch({ executablePath:"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", headless:"new", args:["--no-sandbox"] });
const p = await b.newPage();
await p.setViewport({ width:414, height:896, deviceScaleFactor:2 });
await p.setCookie({ name:"better-auth.session_token", value:COOKIE, domain:"localhost", path:"/" });
await p.goto("http://localhost:3002/dashboard/employee", { waitUntil:"networkidle0", timeout:30000 });
await sleep(900);
await p.screenshot({ path:"/tmp/fix-dash.png", fullPage:true });
await p.evaluate(() => { const x=[...document.querySelectorAll("button")].find(e=>/Find the root/.test(e.textContent||"")); x&&x.click(); });
await sleep(800); await p.screenshot({ path:"/tmp/fix-journey-top.png" });
console.log("done");
await b.close();
