// AUTO-GENERATED from /copy/*.txt by scripts/build-copy.mjs.
// Do NOT edit this file by hand — edit the .txt files in /copy and rebuild.
export const COPY = {
  "login": {
    "pageTitle": "Sign in to CSA",
    "emailLabel": "Email",
    "emailPlaceholder": "you@example.com",
    "passwordLabel": "Password",
    "passwordPlaceholder": "••••••••",
    "errorMessage": "Invalid email or password.",
    "signInButton": "Sign in",
    "signInButtonLoading": "Signing in…",
    "forgotPasswordLink": "Forgot password?",
    "noAccountText": "No account?",
    "signUpLink": "Sign up"
  },
  "signup": {
    "pageTitle": "Create your account",
    "subtitle": "Open to anyone — no invite needed.",
    "nameLabel": "Your name",
    "namePlaceholder": "Aparna",
    "emailLabel": "Email",
    "emailPlaceholder": "you@example.com",
    "passwordLabel": "Password",
    "passwordPlaceholder": "At least 8 characters",
    "defaultError": "Signup failed. Please try again.",
    "createButton": "Create account",
    "createButtonLoading": "Creating account…",
    "haveAccountText": "Already have an account?",
    "signInLink": "Sign in"
  },
  "reset": {
    "pageTitle": "Reset password",
    "subtitle": "Enter your email and we'll send you a reset link.",
    "emailPlaceholder": "you@example.com",
    "sendButton": "Send reset link",
    "sendButtonLoading": "Sending…",
    "backToSignInLink": "Back to sign in",
    "sentTitle": "Check your email",
    "sentBody": "If an account exists for {email}, we sent a reset link. It expires in 1 hour."
  },
  "onboarding": {
    "title": "Let's set you up",
    "subtitle": "A few quick details so your insights feel like yours.",
    "nameLabel": "Your name",
    "namePlaceholder": "Aparna",
    "companyLabel": "Current company",
    "companyPlaceholder": "Kissflow",
    "roleLabel": "Current role",
    "rolePlaceholder": "Product Manager",
    "experienceLabel": "Years of experience",
    "experiencePlaceholder": "5",
    "managerSectionTitle": "Add a manager (optional)",
    "managerNamePlaceholder": "Manager's name",
    "managerEmailPlaceholder": "Manager's email",
    "mentorSectionTitle": "Add a mentor (optional)",
    "mentorNamePlaceholder": "Mentor's name",
    "mentorEmailPlaceholder": "Mentor's email",
    "errorMessage": "Something went wrong. Please try again.",
    "submitButton": "Start using CSA →",
    "submitButtonLoading": "Saving…"
  },
  "checkin": {
    "doneAllCaughtUpTitle": "You're all caught up!",
    "doneAllCaughtUpBody": "No check-ins waiting right now — we'll nudge you when the next one's ready.",
    "doneNiceWorkTitle": "Nice work, {name}!",
    "doneLoggedBody": "That's logged. Every answer sharpens your insights.",
    "seeDashboardButton": "See my dashboard →",
    "continueButton": "Continue",
    "finishButton": "Finish"
  },
  "catchup": {
    "chipPrefix": "Catch-up",
    "defaultWeekLabel": "earlier",
    "saveButton": "Save & next",
    "skipButton": "Skip this for now"
  },
  "followup": {
    "eyebrow": "Welcome back",
    "title": "Following up on your last nudge",
    "recallIntro": "Your score here was a little lower than your recent average, so we suggested:",
    "prompt": "Were you able to act on it?",
    "yesButton": "Yes ✓",
    "notYetButton": "Not yet",
    "journalLabel": "What did you do?",
    "journalPlaceholder": "e.g. Asked my manager for a stretch project in our 1:1…",
    "encouragement": "No worries — life gets busy. Keep it in mind this week; even one small step counts.",
    "saveButton": "Save",
    "notYetSaveButton": "Okay, got it",
    "celebrateTitle": "Love that! 🎉",
    "celebrateBody": "Acting on small things is exactly how your score moves. That's saved to your journal.",
    "continueButton": "Continue →"
  }
} as const;
