/**
 * Turns the owner-editable text files in /copy into a typed module the app
 * imports (lib/copy.generated.ts). Runs automatically before `dev` and `build`
 * (see package.json), so editing a .txt file + restarting shows up in the app.
 *
 * File format (see /copy/README.txt):
 *   - Lines starting with #  →  comments (ignored)
 *   - [A label in brackets]  →  starts a new piece of copy
 *   - the line(s) below it    →  the actual text shown in the app
 *
 * Each /copy/NN_screen.txt becomes COPY.screen.<labelAsKey>.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const copyDir = join(root, "copy");
const outFile = join(root, "lib", "copy.generated.ts");

/** "Sign in button" → "signInButton" (a safe object key). */
function toKey(label) {
  const parts = label
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim()
    .split(/\s+/);
  return parts
    .map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1)))
    .join("");
}

/** "01_login.txt" → "login" (the screen key). */
function toScreen(filename) {
  return toKey(filename.replace(/\.txt$/i, "").replace(/^\d+[_-]?/, ""));
}

function parse(content, file) {
  const out = {};
  let key = null;
  let buf = [];
  const flush = () => {
    if (key !== null) {
      while (buf.length && buf[0].trim() === "") buf.shift();
      while (buf.length && buf[buf.length - 1].trim() === "") buf.pop();
      if (key in out) console.warn(`⚠ duplicate label "${key}" in ${file} — later one wins`);
      out[key] = buf.join("\n");
    }
    buf = [];
  };
  for (const raw of content.split(/\r?\n/)) {
    if (/^\s*#/.test(raw)) continue;
    const m = raw.match(/^\s*\[([^\]]+)\]\s*$/);
    if (m) {
      flush();
      key = toKey(m[1]);
      continue;
    }
    if (key !== null) buf.push(raw);
  }
  flush();
  return out;
}

const files = readdirSync(copyDir)
  .filter((f) => /^\d/.test(f) && f.toLowerCase().endsWith(".txt")) // numbered screens only (skips README)
  .sort();

const screens = {};
for (const f of files) {
  screens[toScreen(f)] = parse(readFileSync(join(copyDir, f), "utf8"), f);
}

const body = JSON.stringify(screens, null, 2);
const ts = `// AUTO-GENERATED from /copy/*.txt by scripts/build-copy.mjs.
// Do NOT edit this file by hand — edit the .txt files in /copy and rebuild.
export const COPY = ${body} as const;
`;

writeFileSync(outFile, ts);
console.log(`✓ copy: ${files.length} screen(s) → lib/copy.generated.ts`);
