/**
 * Turns the owner-editable /copy/copy.html (the single "all app wording" page)
 * into a typed module the app imports (lib/copy.generated.ts). Runs
 * automatically before `dev` and `build` (see package.json), so editing
 * copy.html + restarting shows the new wording in the app.
 *
 * File format: every piece of copy in copy.html lives in
 *   <p ... data-copy="screen.key" ...>The text shown in the app</p>
 * The owner edits the text in a browser (copy.html is its own little editor
 * with a Download button) or in any text editor. This script only reads the
 * data-copy elements — everything else in the file is presentation.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const srcFile = join(root, "copy", "copy.html");
const outFile = join(root, "lib", "copy.generated.ts");

/** Element inner HTML → plain text: <br> → newline, tags stripped, entities decoded. */
function toText(inner) {
  return inner
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<[^>]+>/g, "")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#0?39;/g, "'")
    .replace(/&nbsp;/g, " ")
    .trim();
}

const html = readFileSync(srcFile, "utf8");
const screens = {};
let count = 0;

const re = /<p[^>]*\bdata-copy="([a-zA-Z0-9]+)\.([a-zA-Z0-9]+)"[^>]*>([\s\S]*?)<\/p>/g;
let m;
while ((m = re.exec(html)) !== null) {
  const [, screen, key, inner] = m;
  screens[screen] ??= {};
  if (key in screens[screen]) console.warn(`⚠ duplicate key "${screen}.${key}" in copy.html — later one wins`);
  screens[screen][key] = toText(inner);
  count++;
}

if (count === 0) {
  throw new Error("No data-copy entries found in copy/copy.html — is the file intact?");
}

const body = JSON.stringify(screens, null, 2);
const ts = `// AUTO-GENERATED from /copy/copy.html by scripts/build-copy.mjs.
// Do NOT edit this file by hand — edit copy/copy.html and rebuild.
export const COPY = ${body} as const;
`;

writeFileSync(outFile, ts);
console.log(`✓ copy: ${count} strings across ${Object.keys(screens).length} screen(s) → lib/copy.generated.ts`);
